name: Run Gradle on PRs and Pushes
on: [pull_request, push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: test
        run: ./gradlew test
        
      - if: always()
        name: Upload test result
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: build/reports/**/*
          
      - name: testReport
        run: ./gradlew jacocoTestReport
