name: Run Gradle on PRs and Pushes
on: [pull_request, push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Clean
        run: ./gradlew clean
      - name: Test
        run: ./gradlew test --stacktrace --scan

      - if: always()
        name: Upload test result
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: build/reports/**/*

      - name: testReport
        run: ./gradlew jacocoTestReport
